"""The trading agent's voice and brain.

This module is the 'independent agent' layer: it narrates every decision the
system makes (token-free — the reasoning patterns are authored in, not
generated by an LLM at runtime), assesses market conditions, keeps a learning
ledger, and proposes/applies bounded parameter refinements.

Hard boundary (by design): this agent writes ONLY
    journal/agent_feed.json   — the dashboard's agent timeline
    journal/learning.json     — outcome statistics it learns from
    journal/suggestions.json  — pending/decided improvement proposals
    config_overrides.json     — bounded, whitelisted parameter tweaks
It can never touch risk caps, the strategy rules, the broker, or base config.
"""
import json
import logging
import os
import random
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

log = logging.getLogger("agent")

BASE = Path(__file__).resolve().parent
load_dotenv(BASE / ".env")
JOURNAL = BASE / "journal"
FEED_FILE = JOURNAL / "agent_feed.json"
LEARNING_FILE = JOURNAL / "learning.json"
SUGGESTIONS_FILE = JOURNAL / "suggestions.json"
OVERRIDES_FILE = BASE / "config_overrides.json"

ICONS = {"session_start": "🌅", "session_end": "🏁", "range": "📐", "filtered": "🚫",
         "skipped": "✋", "entry": "📈", "manage": "🛡️", "exit": "💰",
         "assessment": "🧭", "halt": "⛔", "bench": "🪑", "adjustment": "⚙️",
         "suggestion": "💡", "info": "🤖"}

BIAS_LABEL = {"bullish": "🐂 Bullish", "bearish": "🐻 Bearish",
              "consolidation": "↔️ Consolidation"}


def _atomic_write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = str(path) + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, path)


def _load(path, default):
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except Exception as e:
        log.warning("could not read %s: %s", path, e)
    return default


def atr_band(ratio):
    if ratio is None:
        return "na"
    return "<0.75" if ratio < 0.75 else ("0.75-1.5" if ratio <= 1.5 else ">1.5")


class TradingAgent:
    def __init__(self, cfg, replay=False):
        self.cfg = cfg
        self.acfg = cfg.get("agent", {})
        self.tuning = cfg.get("tuning", {})
        self.replay = replay
        self.feed = _load(FEED_FILE, [])
        self.assessments = {}      # asset -> bullish|bearish|consolidation
        self._pending_bias = {}    # debounce: candidate bias must be seen twice
        self._last_manage = {}     # asset -> datetime
        self._last_r_step = {}     # asset -> int (half-R milestones)
        self._cutoff_noted = set()

    # ------------------------------------------------------------------ feed
    def say(self, kind, text, discord=False, now=None):
        t = (now or datetime.now(timezone.utc)).isoformat(timespec="seconds")
        self.feed.append({"t": t, "kind": kind,
                          "icon": ICONS.get(kind, "🤖"), "text": text})
        self.feed = self.feed[-int(self.acfg.get("feed_limit", 300)):]
        _atomic_write(FEED_FILE, json.dumps(self.feed, indent=1))
        log.info("AGENT [%s] %s", kind, text)
        if discord and not self.replay:
            self._discord(f"{ICONS.get(kind, '🤖')} {text}")

    def _discord(self, content):
        url = os.getenv("DISCORD_WEBHOOK_URL")
        if not url:
            return
        try:
            body = json.dumps({"content": content[:1900],
                               "username": "Trading Agent"}).encode()
            req = urllib.request.Request(url, data=body,
                                         headers={"Content-Type": "application/json",
                                                  "User-Agent": "TradingAgent/2.0"})
            urllib.request.urlopen(req, timeout=5).read()
        except Exception as e:
            log.warning("discord notify failed: %s", e)

    # ---------------------------------------------------- market assessment
    def assess(self, asset, bars_1m, now=None):
        """Bullish / bearish / consolidation from 15-min EMA(20) position+slope."""
        try:
            o = bars_1m.resample("15min").agg({"Close": "last"}).dropna()
            period = int(self.acfg.get("assessment_ema_period", 20))
            if len(o) < period + 4:
                return self.assessments.get(asset)
            ema = o["Close"].ewm(span=period, adjust=False).mean()
            price, e_now, e_prev = float(o["Close"].iloc[-1]), float(ema.iloc[-1]), float(ema.iloc[-4])
            if price > e_now and e_now > e_prev:
                bias = "bullish"
            elif price < e_now and e_now < e_prev:
                bias = "bearish"
            else:
                bias = "consolidation"
            old = self.assessments.get(asset)
            if old is not None and bias != old:
                # debounce: a new bias must hold for two consecutive reads
                if self._pending_bias.get(asset) != bias:
                    self._pending_bias[asset] = bias
                    return old
            self._pending_bias.pop(asset, None)
            self.assessments[asset] = bias
            if old is not None and old != bias:
                self.say("assessment",
                         f"{asset} reads {BIAS_LABEL[bias]} now (was {BIAS_LABEL[old]}). "
                         f"Price {price:.2f} vs 15m EMA{period} {e_now:.2f} — "
                         "my directional bias updates with it; the entry trigger is still "
                         "the opening-range break, not this read.", now=now)
            return bias
        except Exception as e:
            log.warning("assessment failed for %s: %s", asset, e)
            return self.assessments.get(asset)

    # ------------------------------------------------------------ narration
    def on_session_start(self, session_label, assets, balance, top_events, now=None):
        ev = ""
        if top_events:
            names = ", ".join(f"{e['title']} ({e['when'].strftime('%H:%M')} UTC)"
                              for e in top_events[:3])
            ev = f" High-impact USD news on watch: {names} — I stand aside around those."
        plan = random.choice([
            "Plan: let the first 15 minutes draw the opening range, validate it against ATR, "
            "then hunt the breakout with a stop at the far side and a 2R target.",
            "Same discipline as always: 15-minute opening range, volatility check, "
            "trade the break, risk 1%, target 2R, flat by the close.",
        ])
        self.say("session_start",
                 f"{session_label} — I'm on watch for {', '.join(assets)} with "
                 f"${balance:,.2f}. {plan}{ev}", discord=True, now=now)

    def on_range_set(self, asset, lo, hi, ratio, now=None):
        bias = self.assessments.get(asset)
        bias_txt = f" Context: {BIAS_LABEL[bias]}." if bias else ""
        self.say("range",
                 f"{asset} opening range is set: {lo}–{hi} ({ratio}x normal 15-min movement — "
                 f"healthy). Now I wait: a 1-minute close above {hi} makes me a buyer, "
                 f"below {lo} a seller. No prediction, just reaction.{bias_txt}", now=now)

    def on_filtered(self, asset, reason, now=None):
        self.say("filtered",
                 f"{asset}: standing aside for this whole session — {reason} "
                 "Patience costs nothing; a forced trade in bad conditions does.",
                 discord=True, now=now)

    def on_skipped(self, asset, direction, why, now=None):
        self.say("skipped",
                 f"A {direction} breakout fired on {asset}, but I'm not taking it: {why} "
                 "The rule exists precisely for moments like this.",
                 discord=True, now=now)

    def on_entry(self, pos, ratio, now=None):
        bias = self.assessments.get(pos["asset"])
        agree = ""
        if bias == "bullish" and pos["direction"] == "LONG" or \
           bias == "bearish" and pos["direction"] == "SHORT":
            agree = " The breakout direction agrees with my broader read — alignment I like to see."
        elif bias and bias != "consolidation":
            agree = (" Worth noting: this fires against my broader read, but the system "
                     "trades the range break, not my opinion — that's the point of being systematic.")
        tv = pos["context"].get("tv_rating", "UNAVAILABLE")
        self.say("entry",
                 f"ENTERED {pos['direction']} {pos['asset']} at {pos['entry_price']} — "
                 f"price closed through the opening range ({ratio}x ATR). "
                 f"Size {pos['units']} units so the stop at {pos['stop']} risks exactly "
                 f"${pos['risk_usd']} (1%). Target {pos['target']} (2R). "
                 f"TradingView 15m read: {tv}.{agree} From here the plan owns the trade: "
                 "stop, target, or session close — whichever comes first.",
                 discord=True, now=now)
        self._last_manage[pos["asset"]] = now or datetime.now(timezone.utc)
        self._last_r_step[pos["asset"]] = 0

    def on_manage(self, asset, pos, cur_r, price, now=None):
        """Throttled: every N minutes, or instantly when a half-R milestone is crossed."""
        now = now or datetime.now(timezone.utc)
        step = int(cur_r * 2)  # half-R milestones
        every = self.acfg.get("manage_update_minutes", 5) * 60
        since = (now - self._last_manage.get(asset, now)).total_seconds()
        due = since >= every
        milestone = step != self._last_r_step.get(asset, 0) and since >= 120
        if not (due or milestone):
            return
        self._last_manage[asset] = now
        self._last_r_step[asset] = step
        if cur_r >= 1.5:
            note = ("Closing in on the 2R target. The rules don't trail or take partials — "
                    "the math needs full winners, so I let it run.")
        elif cur_r >= 0.5:
            note = ("Comfortably in profit. I keep the stop where the structure says it belongs — "
                    "moving it early just donates good trades to noise.")
        elif cur_r >= -0.5:
            note = ("Early innings — price is still negotiating around the range edge. "
                    "Risk is fixed and prepaid; nothing to manage but my patience.")
        else:
            note = ("Pressure on the stop. If it hits, that's a planned 1R loss, not a failure — "
                    "the edge lives across many trades, not this one.")
        self.say("manage",
                 f"{asset} {pos['direction']} update: {price:.2f}, {cur_r:+.2f}R "
                 f"(best so far +{pos.get('mfe', 0):.2f}R). {note}", now=now)

    def on_exit(self, trade, now=None):
        r = trade["r_multiple"]
        reason = {"target": "target hit", "stop": "stopped out", "time": "session-close exit",
                  "news_flatten": "flattened ahead of news",
                  "daily_stop_flatten": "daily-stop flatten"}.get(trade["exit_reason"],
                                                                  trade["exit_reason"])
        lesson = (trade.get("reflection", {}).get("improve") or
                  trade.get("reflection", {}).get("went_well") or [""])[0]
        verdict = "✅ WIN" if trade["pnl"] > 0 else ("❌ LOSS" if trade["pnl"] < 0 else "➖ FLAT")
        self.say("exit",
                 f"CLOSED {trade['direction']} {trade['asset']} at {trade['exit_price']} "
                 f"({reason}) — {verdict} {trade['pnl']:+.2f} USD ({r:+.2f}R) after "
                 f"{trade['duration_min']} min. Balance ${trade['balance_after']:,.2f}. "
                 f"Lesson: {lesson}", discord=True, now=now)

    def on_halt(self, reason, now=None):
        self.say("halt",
                 f"Risk system engaged: {reason}. This is the system protecting the account — "
                 "the worst days are capped by design, and tomorrow starts clean.",
                 discord=True, now=now)

    def on_bench(self, asset, streak, now=None):
        self.say("bench",
                 f"{asset} benched after {streak} consecutive losses. When an asset keeps "
                 "failing the same setup, the cheapest fix is distance — it sits out a day "
                 "while I keep collecting data.", discord=True, now=now)

    def on_session_end(self, session_label, trades, balance, now=None):
        if trades:
            wins = sum(1 for t in trades if t["pnl"] > 0)
            pnl = sum(t["pnl"] for t in trades)
            avg_r = sum(t["r_multiple"] for t in trades) / len(trades)
            self.say("session_end",
                     f"{session_label} done: {len(trades)} trades, {wins} wins, "
                     f"{pnl:+.2f} USD ({avg_r:+.2f}R avg). Balance ${balance:,.2f}. "
                     "Every trade is archived with its reasoning — the ledger gets smarter "
                     "even when the P&L doesn't.", discord=True, now=now)
        else:
            self.say("session_end",
                     f"{session_label} done: no trades. The filters and caps kept me flat — "
                     f"a day of not losing is a perfectly good day. Balance ${balance:,.2f}.",
                     discord=True, now=now)

    # ------------------------------------------------------------- learning
    def learn_from_trade(self, trade, minutes_into_session):
        led = _load(LEARNING_FILE, {"buckets": {}, "adjustments_used": 0,
                                    "trades_seen": 0, "trades_at_last_change": 0,
                                    "last_change_day": None, "history": []})
        ctx = trade.get("context", {})
        tv = ctx.get("tv_rating", "UNAVAILABLE")
        if tv in ("UNAVAILABLE", "BACKTEST"):
            tv_key = "na"
        elif (trade["direction"] == "LONG") == (tv in ("BUY", "STRONG_BUY")):
            tv_key = "agree"
        else:
            tv_key = "neutral"
        keys = [f"asset:{trade['asset']}", f"session:{trade['session']}",
                f"range:{atr_band(ctx.get('range_atr_ratio'))}",
                f"hour:{'first' if minutes_into_session <= 60 else 'later'}",
                f"tv:{tv_key}"]
        for k in keys:
            b = led["buckets"].setdefault(k, {"trades": 0, "wins": 0, "sum_r": 0.0})
            b["trades"] += 1
            b["wins"] += 1 if trade["pnl"] > 0 else 0
            b["sum_r"] = round(b["sum_r"] + trade["r_multiple"], 2)
        led["trades_seen"] += 1
        _atomic_write(LEARNING_FILE, json.dumps(led, indent=1))

    def review_and_refine(self, day_key, now=None):
        """End of session: turn bucket statistics into at most ONE refinement.

        First `auto_budget` changes auto-apply (bounded); afterwards everything
        becomes a suggestion awaiting approval on the dashboard.
        """
        if self.replay:
            return
        led = _load(LEARNING_FILE, None)
        if not led:
            return
        candidate = self._find_candidate(led)
        if not candidate:
            return
        # evidence gates: enough new trades, enough days since the last change
        if led["trades_seen"] - led.get("trades_at_last_change", 0) < \
                self.tuning.get("min_trades_per_change", 20):
            return
        last_day = led.get("last_change_day")
        if last_day:
            gap = (datetime.fromisoformat(day_key) - datetime.fromisoformat(last_day)).days
            if gap < self.tuning.get("min_days_between_changes", 5):
                return

        used, budget = led.get("adjustments_used", 0), self.tuning.get("auto_budget", 15)
        if used < budget:
            if self._apply_override(candidate["param"], candidate["to"]):
                used += 1
                led["adjustments_used"] = used
                led["trades_at_last_change"] = led["trades_seen"]
                led["last_change_day"] = day_key
                led["history"].append({"day": day_key, "auto": True, **candidate})
                _atomic_write(LEARNING_FILE, json.dumps(led, indent=1))
                self.say("adjustment",
                         f"Refinement {used}/{budget} applied: {candidate['param']} "
                         f"{candidate['from']} → {candidate['to']}. Why: {candidate['why']} "
                         f"Evidence: {candidate['evidence']}. Small step, hard bounds, "
                         "and the risk caps are untouchable by design.",
                         discord=True, now=now)
        else:
            sugg = _load(SUGGESTIONS_FILE, [])
            if any(s["param"] == candidate["param"] and s["status"] == "pending"
                   for s in sugg):
                return
            sid = f"sg{int(datetime.now(timezone.utc).timestamp())}"
            sugg.append({"id": sid, "created": day_key, "status": "pending", **candidate})
            _atomic_write(SUGGESTIONS_FILE, json.dumps(sugg, indent=1))
            self.say("suggestion",
                     f"Suggestion (my {budget} auto-refinements are spent): change "
                     f"{candidate['param']} from {candidate['from']} to {candidate['to']}. "
                     f"{candidate['why']} Evidence: {candidate['evidence']}. "
                     "Approve or reject it on the dashboard — I won't touch it otherwise.",
                     discord=True, now=now)

    def _find_candidate(self, led):
        min_n = self.tuning.get("min_bucket_trades", 10)
        strat = self.cfg["strategy"]
        wl = self.tuning.get("whitelist", {})

        def bucket(k):
            b = led["buckets"].get(k)
            if b and b["trades"] >= min_n:
                return b["trades"], b["sum_r"] / b["trades"]
            return None, None

        rules = []
        n, avg = bucket("range:<0.75")
        if avg is not None and avg <= -0.35:
            p = "strategy.range_atr_min"
            to = round(strat["range_atr_min"] + wl[p]["step"], 2)
            rules.append((avg, {"param": p, "from": strat["range_atr_min"], "to": to,
                                "why": "Small opening ranges keep producing fakeouts; "
                                       "demanding a livelier range filters them out.",
                                "evidence": f"{n} trades with range <0.75x ATR averaged {avg:+.2f}R"}))
        n, avg = bucket("range:>1.5")
        if avg is not None and avg <= -0.35:
            p = "strategy.range_atr_max"
            to = round(strat["range_atr_max"] - wl[p]["step"], 2)
            rules.append((avg, {"param": p, "from": strat["range_atr_max"], "to": to,
                                "why": "Oversized opening ranges (news-driven) keep losing; "
                                       "tightening the ceiling avoids them.",
                                "evidence": f"{n} trades with range >1.5x ATR averaged {avg:+.2f}R"}))
        n, avg = bucket("hour:later")
        if avg is not None and avg <= -0.35:
            p = "strategy.entry_cutoff_minutes"
            to = int(strat.get("entry_cutoff_minutes", 0) + wl[p]["step"])
            rules.append((avg, {"param": p, "from": strat.get("entry_cutoff_minutes", 0),
                                "to": to,
                                "why": "Late-session entries lack the time to reach 2R; "
                                       "cutting off late entries protects the average.",
                                "evidence": f"{n} late entries averaged {avg:+.2f}R"}))
        valid = []
        for avg, cand in rules:
            lim = wl[cand["param"]]
            if "bool" in lim or (lim["min"] <= cand["to"] <= lim["max"]):
                if cand["to"] != cand["from"]:
                    valid.append((avg, cand))
        if not valid:
            return None
        valid.sort(key=lambda x: x[0])  # worst-performing bucket first
        return valid[0][1]

    def _apply_override(self, param, value):
        wl = self.tuning.get("whitelist", {})
        lim = wl.get(param)
        if lim is None:
            log.error("refused override for non-whitelisted param %s", param)
            return False
        if "bool" not in lim and not (lim["min"] <= value <= lim["max"]):
            log.error("refused out-of-bounds override %s=%s", param, value)
            return False
        ov = _load(OVERRIDES_FILE, {})
        ov[param] = value
        _atomic_write(OVERRIDES_FILE, json.dumps(ov, indent=1))
        return True

    def apply_approved_suggestions(self, now=None):
        if self.replay:
            return
        sugg = _load(SUGGESTIONS_FILE, [])
        changed = False
        for s in sugg:
            if s["status"] == "approved":
                ok = self._apply_override(s["param"], s["to"])
                s["status"] = "applied" if ok else "rejected"
                changed = True
                if ok:
                    self.say("adjustment",
                             f"You approved it, so it's in effect now: {s['param']} "
                             f"{s['from']} → {s['to']}. ({s['why']})",
                             discord=True, now=now)
        if changed:
            _atomic_write(SUGGESTIONS_FILE, json.dumps(sugg, indent=1))
        return changed

    # ------------------------------------------------------- dashboard data
    def dashboard_payload(self):
        led = _load(LEARNING_FILE, {})
        sugg = _load(SUGGESTIONS_FILE, [])
        return {
            "feed": self.feed[-120:][::-1],
            "assessments": self.assessments,
            "suggestions": {
                "pending": [s for s in sugg if s["status"] == "pending"],
                "history": ([s for s in sugg if s["status"] != "pending"][-10:][::-1] +
                            led.get("history", [])[-10:][::-1]),
                "used": led.get("adjustments_used", 0),
                "budget": self.tuning.get("auto_budget", 15),
            },
            "overrides": _load(OVERRIDES_FILE, {}),
        }
